### ISSUE TITLE
설문 참여 선물 저장 API 구현

### ISSUE THREAD

**Issue by hjun0917** [form-maker/FFF-BE#172]
# Description

설문에 참여한 인원들 중 추첨을 통해 전달할 선물에 대한 정보를 담는 API 구현

## Todo

- [ ] 메인 페이지 설문 조회 API 수정
- [x] 설문 생성 API 수정
- [ ] 설문 조회 APi 수정
- [x] gift 엔티티 추가
- [ ] 이외 관련되어 추가사항들 추가하기

## Etc

기타사항
