### ISSUE TITLE
다운로드 로직 확인 및 변경

### ISSUE THREAD

**Issue by faulty337** [form-maker/FFF-BE#229]
## Description
다운로드 진행 시 Query와 java로직에서 비교 후 성능 체크 필요

## Before
현재 다운로드 진행 시 응답 수 만큼  query가 날아감

## After
응답을 전체 가져오고 로직을 통해 분리

## Todo
- [ ] 기존 로직 시간 체크
- [ ] 다운로드 로직 변경
- [ ] 변경된 로직 시간 체크
