### ISSUE TITLE
설문 상태 수정

### ISSUE THREAD

**Issue by faulty337** [form-maker/FFF-BE#45]
## Description
설문의 상태 수정
isDone -> status
Status enum처리 필요
수정에 관하여 이를 Response하는 곳 까지의 수정 작업 필수

## Before
설문의 상태가 2가지(진행, 종료)가 아닌 3가지(시작전, 진행, 종료)로 나뉨에 따른 변경

## After
Status Enum을 이용하여 해당값을 고정

## Todo
- [ ] Status Enum 제작
- [ ] Entity 컬럼 수정
- [ ] isDone 사용 부분 수정
