### ISSUE TITLE
설문 문제 컬럼 변경

### ISSUE THREAD

**Issue by faulty337** [form-maker/FFF-BE#49]
# Description
설문 문제에 대한 설명하는 데이터를 담을 컬럼 추가 필요
기존 minValue, MaxValue -> volume 으로 변경

## Todo

- [ ] summary 컬럼 추가
- [ ] volume 컬럼 변경
- [ ] 추가에 따른 사용처 부분 수정 필요
