### ISSUE TITLE
Reply 저장 기능 수정

### ISSUE THREAD

**Issue by faulty337** [form-maker/FFF-BE#84]
## Description
Reply 저장 방식이 단일 -> 리스트로 수정

## Before
응답에 대한 데이터가 현재 한 개의 응답만 받고 있는 형태

## After
한 설문에 대한 모든 응답을 한꺼번에 처리

## Todo
- [x] 응답 Request 방식 수정
- [ ] 응답 저장 시 해당 문제의 form에 따라 다른 방식으로 저장(Rank)
- [x] 불필요한 Stats 컬럼 삭제
- [x] selectValue 자료형 변경(String)
